import { Song } from './types';
import songsData from './songs.json';

// Load songs from JSON file
export const songPool: Song[] = songsData as unknown as Song[];

// Legacy hardcoded songs (kept as backup, can be removed)
export const legacySongPool: Song[] = [
  // 1950s-60s (verified Spotify IDs)
  { id: '1', spotifyId: '2RsAajgo0g7bMCHxwH3Sk0', title: "Rock Around the Clock", artist: "Bill Haley", year: 1954 },
  { id: '2', spotifyId: '4bBrKDo7oLpBLDdwqbVJfh', title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958 },
  { id: '3', spotifyId: '64Oc6xpVgQezxN3VDib5jy', title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957 },
  { id: '4', spotifyId: '4pbG9SUmWIvsROVLF0zF9s', title: "I Want to Hold Your Hand", artist: "The Beatles", year: 1963 },
  { id: '5', spotifyId: '0aym2LBJBk9DAYuHHutrIl', title: "Hey Jude", artist: "The Beatles", year: 1968 },
  { id: '6', spotifyId: '2PzU4IB8Dr6mxV3lHuaG34', title: "Satisfaction", artist: "The Rolling Stones", year: 1965 },
  { id: '7', spotifyId: '7s25THrKz86DM225dOYwnr', title: "Respect", artist: "Aretha Franklin", year: 1967 },
  { id: '8', spotifyId: '0wJoRiX5K5BxlqZTolB2LD', title: "Purple Haze", artist: "Jimi Hendrix", year: 1967 },
  { id: '9', spotifyId: '5uvosCdMlFdTXhoazkTI5R', title: "Light My Fire", artist: "The Doors", year: 1967 },
  { id: '10', spotifyId: '3SdTKo2uVsxFblQjpScoHy', title: "Stand By Me", artist: "Ben E. King", year: 1961 },

  // 1970s
  { id: '11', spotifyId: '40riOy7x9W7GXjyGp4pjAv', title: "Hotel California", artist: "Eagles", year: 1976 },
  { id: '12', spotifyId: '7tFiyTwD0nx5a1eklYtX2J', title: "Bohemian Rhapsody", artist: "Queen", year: 1975 },
  { id: '13', spotifyId: '5CQ30WqJwcep0pYcV4AMNc', title: "Stairway to Heaven", artist: "Led Zeppelin", year: 1971 },
  { id: '14', spotifyId: '7pKfPomDEeI4TPT6EOYjn9', title: "Imagine", artist: "John Lennon", year: 1971 },
  { id: '15', spotifyId: '70oAhYqhDiVJJTlnogT4xt', title: "Stayin' Alive", artist: "Bee Gees", year: 1977 },
  { id: '16', spotifyId: '0GjEhVFGZW8afUYGChu3Rr', title: "Dancing Queen", artist: "ABBA", year: 1976 },
  { id: '17', spotifyId: '1h2xVEoJORqrg71HocgqXd', title: "Superstition", artist: "Stevie Wonder", year: 1972 },
  { id: '18', spotifyId: '54flyrjcdnQdco7300avMJ', title: "We Will Rock You", artist: "Queen", year: 1977 },
  { id: '19', spotifyId: '2zYzyRzz6pRmhPzyfMEC8s', title: "Highway to Hell", artist: "AC/DC", year: 1979 },
  { id: '20', spotifyId: '5T8EDUDqKcs6OSOwEsfqG7', title: "Don't Stop Me Now", artist: "Queen", year: 1978 },

  // 1980s
  { id: '21', spotifyId: '7J1uxwnxfQLu4APicE5Rnj', title: "Billie Jean", artist: "Michael Jackson", year: 1982 },
  { id: '22', spotifyId: '3BovdzfaX4jb5KFQwoPfAw', title: "Beat It", artist: "Michael Jackson", year: 1982 },
  { id: '23', spotifyId: '2LlQb7Uoj1kKyGhlkBf9aC', title: "Thriller", artist: "Michael Jackson", year: 1982 },
  { id: '24', spotifyId: '1ZPlNanZsIaLKCT8hSjCdS', title: "Like a Virgin", artist: "Madonna", year: 1984 },
  { id: '25', spotifyId: '2WfaOiMkCvy7F5fcp2zZ8L', title: "Take On Me", artist: "a-ha", year: 1985 },
  { id: '26', spotifyId: '0J6mQxEZnlRt9ymzFntA6z', title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986 },
  { id: '27', spotifyId: '7o2CTH4ctstm8TNelqjb51', title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { id: '28', spotifyId: '4bHsxqR3GMrXTxEPLuK5ue', title: "Don't Stop Believin'", artist: "Journey", year: 1981 },
  { id: '29', spotifyId: '2374M0fQpWi3dLnB54qaLX', title: "Africa", artist: "Toto", year: 1982 },
  { id: '30', spotifyId: '4PTG3Z6ehGkBFwjybzWkR8', title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987 },
  { id: '31', spotifyId: '1JSTJqkT5qHq8MDJnJbRE1', title: "Every Breath You Take", artist: "The Police", year: 1983 },
  { id: '32', spotifyId: '6ADSaE87h8Y3lccZlBJdXH', title: "With or Without You", artist: "U2", year: 1987 },
  { id: '33', spotifyId: '2A59jD3yBxel91DPUyHGwz', title: "When Doves Cry", artist: "Prince", year: 1984 },
  { id: '34', spotifyId: '54X78diSLoUDI3joC2bjMz', title: "Purple Rain", artist: "Prince", year: 1984 },
  { id: '35', spotifyId: '08mG3Y1vljYA6bvDt4Wqkj', title: "Back in Black", artist: "AC/DC", year: 1980 },

  // 1990s
  { id: '36', spotifyId: '1f6IRdPfdFknEldlb7pFLF', title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991 },
  { id: '37', spotifyId: '3ZOEytgrvLwQaqXreDs2Jx', title: "Wonderwall", artist: "Oasis", year: 1995 },
  { id: '38', spotifyId: '4VqPOruhp5EdPBeR92t6lQ', title: "Creep", artist: "Radiohead", year: 1992 },
  { id: '39', spotifyId: '3AJwUDP919kvQ9QcozQPxg', title: "Under the Bridge", artist: "RHCP", year: 1991 },
  { id: '40', spotifyId: '3YRCqOhFifThpSRFJ1VWFM', title: "Losing My Religion", artist: "R.E.M.", year: 1991 },
  { id: '41', spotifyId: '1301WleyT98MSxVHPZCA6M', title: "Gangsta's Paradise", artist: "Coolio", year: 1995 },
  { id: '42', spotifyId: '3OHfY25tqY28d16oZczHc8', title: "Wannabe", artist: "Spice Girls", year: 1996 },
  { id: '43', spotifyId: '54KFQB6N4pn926IUUYZGzK', title: "I Want It That Way", artist: "Backstreet Boys", year: 1999 },
  { id: '44', spotifyId: '2TpxZ7JUBn3uw46aR7qd6V', title: "All Star", artist: "Smash Mouth", year: 1999 },
  { id: '45', spotifyId: '3SktMqZmo3M9zbB7oKMIF7', title: "Iris", artist: "Goo Goo Dolls", year: 1998 },
  { id: '46', spotifyId: '2aoo2jlRnM3S0IcjLCODIb', title: "Enter Sandman", artist: "Metallica", year: 1991 },
  { id: '47', spotifyId: '1hKdDCpiI9mqz1jVHRKG0E', title: "Nothing Else Matters", artist: "Metallica", year: 1991 },
  { id: '48', spotifyId: '77S1VHtfTWYJqRfwPBhBYB', title: "I Will Survive", artist: "Gloria Gaynor", year: 1978 },
  { id: '49', spotifyId: '7lPN2DXiMsVn7XUKtOW1CS', title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997 },
  { id: '50', spotifyId: '2nLtzopw4rPReszdYBJU6h', title: "Zombie", artist: "The Cranberries", year: 1994 },

  // 2000s
  { id: '51', spotifyId: '0F7FA14euOIX8KcbEturGH', title: "Mr. Brightside", artist: "The Killers", year: 2003 },
  { id: '52', spotifyId: '20I6sIOMTCkB6w7ryavxtO', title: "Seven Nation Army", artist: "White Stripes", year: 2003 },
  { id: '53', spotifyId: '2d8cediJBnuGxdEf9Dgtmf', title: "Hey Ya!", artist: "OutKast", year: 2003 },
  { id: '54', spotifyId: '5W3cjX2J3tjhG8zb6u0qHn', title: "Clocks", artist: "Coldplay", year: 2002 },
  { id: '55', spotifyId: '1mea3bSkSGXuIRvnydlB5b', title: "Viva la Vida", artist: "Coldplay", year: 2008 },
  { id: '56', spotifyId: '7ygpwy2qP3NbrxVkHvUhXY', title: "Toxic", artist: "Britney Spears", year: 2003 },
  { id: '57', spotifyId: '6habFhsOp2NvshLv26DqMb', title: "Crazy in Love", artist: "Beyoncé", year: 2003 },
  { id: '58', spotifyId: '1zi7xx7UVEFkmKfv06H8x0', title: "Umbrella", artist: "Rihanna", year: 2007 },
  { id: '59', spotifyId: '4VbDJMkAX3dWNBdn3KH6Wx', title: "Rehab", artist: "Amy Winehouse", year: 2006 },
  { id: '60', spotifyId: '3xJSLOVBegPdzyF8NDsVgF', title: "Poker Face", artist: "Lady Gaga", year: 2008 },
  { id: '61', spotifyId: '4WQMEWWXVWGZGcdWVrLmvL', title: "Lose Yourself", artist: "Eminem", year: 2002 },
  { id: '62', spotifyId: '0SF8VbhIJXOvG7buVLJ3WJ', title: "Gold Digger", artist: "Kanye West", year: 2005 },
  { id: '63', spotifyId: '6xGruZOHLs39ZbVccQTuPZ', title: "Crazy", artist: "Gnarls Barkley", year: 2006 },
  { id: '64', spotifyId: '60a0Rd6pjrkxjPbaKzXjfq', title: "In the End", artist: "Linkin Park", year: 2000 },
  { id: '65', spotifyId: '2xLMifQCjDGFmkHkpNLD9h', title: "Bring Me to Life", artist: "Evanescence", year: 2003 },

  // 2010s
  { id: '66', spotifyId: '0tgVpDi06FyKpA1z0VMD4v', title: "Perfect", artist: "Ed Sheeran", year: 2017 },
  { id: '67', spotifyId: '7qiZfU4dY1lWllzX7mPBI3', title: "Shape of You", artist: "Ed Sheeran", year: 2017 },
  { id: '68', spotifyId: '2Fxmhks0bxGSBdJ92vM42m', title: "Bad Guy", artist: "Billie Eilish", year: 2019 },
  { id: '69', spotifyId: '5tYfRbRlp1LZcqK3TN7LdI', title: "Rolling in the Deep", artist: "Adele", year: 2010 },
  { id: '70', spotifyId: '7uv632EkfwYhXoqf8rhYrg', title: "Hello", artist: "Adele", year: 2015 },
  { id: '71', spotifyId: '60nZcImufyMA1MKQY3dcCH', title: "Happy", artist: "Pharrell Williams", year: 2013 },
  { id: '72', spotifyId: '32OlwWuMpZ6b0aN2RZOeMS', title: "Uptown Funk", artist: "Bruno Mars", year: 2014 },
  { id: '73', spotifyId: '0VjIjW4GlUZAMYd2vXMi3b', title: "Despacito", artist: "Luis Fonsi", year: 2017 },
  { id: '74', spotifyId: '2Foc5Q5nqNiosCNqttzHof', title: "Get Lucky", artist: "Daft Punk", year: 2013 },
  { id: '75', spotifyId: '6RUKPb4LETWmmr3iAEQktW', title: "Wake Me Up", artist: "Avicii", year: 2013 },
  { id: '76', spotifyId: '7qEHsqek33rTcFNT9PFqLf', title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2011 },
  { id: '77', spotifyId: '6lanRgr6wXibZr8KgzXxBl', title: "Royals", artist: "Lorde", year: 2013 },
  { id: '78', spotifyId: '3ee8Jmje8o58CHK66QrVC2', title: "Sorry", artist: "Justin Bieber", year: 2015 },
  { id: '79', spotifyId: '2H1gACDYNiGjl78OhQyBPR', title: "Shake It Off", artist: "Taylor Swift", year: 2014 },
  { id: '80', spotifyId: '7KXjTSCq5nL1LoYtL7XAwS', title: "HUMBLE.", artist: "Kendrick Lamar", year: 2017 },
  { id: '81', spotifyId: '2HbKqm4o0w5wEeEFXm2sD4', title: "God's Plan", artist: "Drake", year: 2018 },
  { id: '82', spotifyId: '5Z01UMMf7V1o0MzF86s6WJ', title: "Closer", artist: "The Chainsmokers", year: 2016 },
  { id: '83', spotifyId: '6PCUP3dWmTjcTtXY02oFdT', title: "Havana", artist: "Camila Cabello", year: 2017 },
  { id: '84', spotifyId: '2dHHgzDwk4BJdRwy9uXhTO', title: "Old Town Road", artist: "Lil Nas X", year: 2019 },
  { id: '85', spotifyId: '3CRDbSIZ4r5MsZ0YwxuEkn', title: "Stressed Out", artist: "Twenty One Pilots", year: 2015 },
  { id: '86', spotifyId: '69uxyAqqPIsUyTOTqJCKH1', title: "Counting Stars", artist: "OneRepublic", year: 2013 },
  { id: '87', spotifyId: '5HCyWlXZPP0y6Gqq8TgA20', title: "Somebody That I Used to Know", artist: "Gotye", year: 2011 },
  { id: '88', spotifyId: '4BP3uh0hFLFRb5cjsgLqDh', title: "Pumped Up Kicks", artist: "Foster the People", year: 2010 },
  { id: '89', spotifyId: '2PzU4IB8Dr6mxV3lHuaG34', title: "Let Her Go", artist: "Passenger", year: 2012 },
  { id: '90', spotifyId: '4cOdK2wGLETKBW3PvgPWqT', title: "Take Me to Church", artist: "Hozier", year: 2013 },

  // 2020s
  { id: '91', spotifyId: '0VjIjW4GlUZAMYd2vXMi3b', title: "Blinding Lights", artist: "The Weeknd", year: 2019 },
  { id: '92', spotifyId: '6UelLqGlWMcVH1E5c4H7lY', title: "Watermelon Sugar", artist: "Harry Styles", year: 2019 },
  { id: '93', spotifyId: '2ekn2ttSfGqwhhate0LSR0', title: "Don't Start Now", artist: "Dua Lipa", year: 2019 },
  { id: '94', spotifyId: '3Ofmpyhv5UAQ70mENzB277', title: "Levitating", artist: "Dua Lipa", year: 2020 },
  { id: '95', spotifyId: '5QO79kh1waicV47BqGRL3g', title: "Save Your Tears", artist: "The Weeknd", year: 2020 },
  { id: '96', spotifyId: '4Dvkj6JhhA12EX05fT7y2e', title: "Peaches", artist: "Justin Bieber", year: 2021 },
  { id: '97', spotifyId: '3Wrjm47oTz2sjIgck11l5e', title: "good 4 u", artist: "Olivia Rodrigo", year: 2021 },
  { id: '98', spotifyId: '5HCyWlXZPP0y6Gqq8TgA20', title: "drivers license", artist: "Olivia Rodrigo", year: 2021 },
  { id: '99', spotifyId: '7qiZfU4dY1lWllzX7mPBI3', title: "Stay", artist: "Kid Laroi & Justin Bieber", year: 2021 },
  { id: '100', spotifyId: '1BxfuPKGuaTgP7aM0Bbdwr', title: "As It Was", artist: "Harry Styles", year: 2022 },
];
